### ISSUE TITLE
Undefined compiler version

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qxl.packagebrowser#5]
Since 7 version there is no compiler version in Manifest.json but in Package Browser this line is still showed up:
![Снимок экрана от 2023-01-09 12-21-08](https://user-images.githubusercontent.com/22189134/211275755-c3783cff-d8b5-4071-bc16-d7f7e2d0cffe.png)

**Comment by cboulanger** [comment]
Thanks for catching this. Can you create a PR removing https://github.com/qooxdoo/qxl.packagebrowser/blob/85f4ba1710973450392a6c6e65182171664555cf/source/class/qxl/packagebrowser/PackageBrowser.js#L940-L941 ? Thank you.
